host_type = {
    "blue": ["blue", "driving_blue", "rvr"],
    "browser": ["training_framework"],
    "cloud_dev": [
        "blue",
        "bracket",
        "CV",
        "dart",
        "image_classifier",
        "training_framework",
        "yolov5",
    ],
    "dev": [
        "blue",
        "blue_wiki",
        "bracket",
        "browser",
        "CV",
        "dart",
        "Kanata",
        "image_classifier",
        "training_framework",
        "yolov5",
    ],
    "worker": [
        "blue",
        "blue_wiki",
        "bracket",
        "dart",
        "Kanata",
        "training_framework",
        "worker",
    ],
}
