host_type = {
    "blue": ["blue", "driving_blue", "rvr"],
    "browse": ["training_framework"],
    "cloud_dev": [
        "blue",
        "abcli",
        "bracket",
        "CV",
        "dart",
        "training_framework",
        "yolov5",
    ],
    "dev": [
        "blue",
        "abcli",
        "bracket",
        "CV",
        "dart",
        "Kanata",
        "training_framework",
        "wiki",
        "yolov5",
    ],
    "worker": [
        "blue",
        "abcli",
        "bracket",
        "dart",
        "Kanata",
        "training_framework",
        "wiki",
        "worker",
    ],
}
